server {
    listen 80;
    client_max_body_size 2m;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 "OK\n";
    }



    location /api/auth/ {
        proxy_pass http://auth-service:8000;
        include /etc/nginx/proxy_params.conf;
    }

    location /api/products {
        proxy_pass http://catalog-service:8000;
        include /etc/nginx/proxy_params.conf;
    }

    location /api/internal/ {
        proxy_pass http://catalog-service:8000;
        include /etc/nginx/proxy_params.conf;
    }

    location /api/cart {
        proxy_pass http://cart-service:8000;
        include /etc/nginx/proxy_params.conf;
    }

    location /api/orders {
        proxy_pass http://order-service:8000;
        include /etc/nginx/proxy_params.conf;
    }

    location /api/payments {
        proxy_pass http://payment-service:8000;
        include /etc/nginx/proxy_params.conf;
    }
}
